env:
  browser: true
extends: airbnb-base
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-var: 0
  vars-on-top: 0
  prefer-template: 0
  object-shorthand: 0
  func-names: 0
  prefer-arrow-callback: 0
  max-len: 0