language: node_js
node_js:
- 7
cache:
  directories:
  - node_modules
script:
- gulp
deploy:
  provider: gcs
  access_key_id: GOOG1EZJMYMWQGJASCASF7BTALY7KGYYMI7YS5VCHDGJJXFF46FJRNII4OFZY
  secret_access_key:
    secure: P6zsiyTF+bl4WaMsq8difRnVwLN+yRuJktW5NJWzItCRMuP8odD932QLBDeYucf0k95SD9gsKZS4FpeX+oGc4QfPH2ow5TureXWIfJbaZ1/U89DwsqmqciWLvJe5BvZLObXb22gYq7XkkF8iGX7mL96LtcZDWaWlB3mbV9lb5M6JpB7/BCuPFaENn7jcfLYJjZkPGOMyVxl6fxoHizBJoMsmhujnHhKCpdahLB7BJsBKAhl8Fq/Su77vMLOKYqUS8j2lnYBfL3Yw4fTb+nSAL/bXnhowfnhvDU+3P5IpjvsTk9OaL6oFQ+j/AxqvRQQsaCorJFwzOpbqbxzioqweJ6OEp9F5fk2NtDHzto3/uRWmmlvFU5pS3NCuphSyxHQ2eHGJuLG5HFWg32TPkof2NVB8V/5kVRlkXL88Zz18yCOL01R6N3vwCgZ0v6qUK8YulfZb1gg3m7svkG0wP+fNibUmrJ1TLq9H2YmHs9x/+KLhhBomJcOQo0ufcIWpS2yJLqQgagtfo8cCpSSZaovdIj1HMYSFamuI7CQs7pEtWjjQsE/DuTRBFrMZ+ufAfmmrIUOLAy3tf7M35GMZmO4fdWXAnZFUQF5dCcCmfqsiT3isjANcR6o2GSdkhFSJfaPdY8rdia9gmvibR26viBYUG+AN1QtCiL4plhoN46L5H6o=
  bucket: www.saferinsulin.org
  local-dir: dist
  skip_cleanup: true
  acl: "public-read"
  detect_encoding: true
  cache_control: "no-cache"
  on:
    branch: master
    repo: jplomas/saferinsulin
