var express = require('express');
var calc = require('insulin-calc/js/insulin-calc');

var router = express.Router();

/**
 * @api {get} /check/:governance Governance hexcode check
 * @apiName GetCheck
 * @apiGroup GET
 * @apiVersion 1.0.0
 *
 * @apiParam {String} governance Governance hexcode generated by the saferinsulin.org algorithm
 *
 * @apiSuccess {String} function Calculator function called: 'a' (start) or 'b' (continue).
 * @apiSuccess {Number} current Current glucose parameter passed to function
 * @apiSuccess {Number} last Previous glucose parameter passed to function [b only]
 * @apiSuccess {Number} rate Rate parameter passed to function [b only]
 * @apiSuccess {String} date Date the function was invoked
 */
router.get('/:hex', function (req, res, next) {
  var result = calc.governance(req.params.hex);
  res.send(result);
});

module.exports = router;
